# Server Configuration
server:
  port: 8080

# Spring Boot Configuration
spring:
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:insurancedb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console # Enable H2 web console at http://localhost:8080/h2-console
  # Java Persistence API Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true # Defer data.sql execution until after Hibernate has created the schema

# OpenAPI (Springdoc) Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  paths-to-match:
    - /api/** # Only document endpoints under /api/ path