openapi: 3.0.3
info:
  title: Insurance Company API
  description: A dummy API for an insurance company to manage customers, policies, and claims.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local Development server

# Paths are now defined correctly by referencing external files for each path item.
paths:
  /customers:
    $ref: './paths/customers_collection.yaml'
  /customers/{id}:
    $ref: './paths/customers_item.yaml'
  /customers/search:
    $ref: './paths/customers_search.yaml'
  /customers/{id}/policies:
    $ref: './paths/customer_policies_collection.yaml'
  /policies:
    $ref: './paths/policies_collection.yaml'
  /policies/search:
    $ref: './paths/policies_search.yaml'
  /policies/{id}:
    $ref: './paths/policies_item.yaml'
  /policies/{policyId}/auto-claims:
    $ref: './paths/auto_claims_by_policy.yaml'
  /policies/{policyId}/home-claims:
    $ref: './paths/home_claims_by_policy.yaml'
  /policies/{policyId}/health-claims:
    $ref: './paths/health_claims_by_policy.yaml'
  # Auto Claims specific endpoints
  /auto-claims:
    $ref: './paths/auto_claims_collection.yaml'
  /auto-claims/{id}:
    $ref: './paths/auto_claims_item.yaml'
  /auto-claims/{id}/assign-adjuster:
    $ref: './paths/auto_claims_assignment.yaml'
  # Home Claims specific endpoints
  /home-claims:
    $ref: './paths/home_claims_collection.yaml'
  /home-claims/{id}:
    $ref: './paths/home_claims_item.yaml'
  /home-claims/{id}/assign-adjuster:
    $ref: './paths/home_claims_assignment.yaml'
  # Health Claims specific endpoints
  /health-claims:
    $ref: './paths/health_claims_collection.yaml'
  /health-claims/{id}:
    $ref: './paths/health_claims_item.yaml'
  /health-claims/{id}/assign-adjuster:
    $ref: './paths/health_claims_assignment.yaml'
  /employees:
    $ref: './paths/employees_collection.yaml'
  /employees/{id}:
    $ref: './paths/employees_item.yaml'
  /policy-conditions:
    $ref: './paths/policy_conditions.yaml'
  /agencies:
    $ref: './paths/agencies_collection.yaml'
  /agencies/{id}:
    $ref: './paths/agencies_item.yaml'

# Components and schemas remain the same.
components:
  schemas:
    CustomerDto:
      $ref: './components/schemas/CustomerDto.yaml'
    AddressDto:
      $ref: './components/schemas/AddressDto.yaml'
    PolicyDto:
      $ref: './components/schemas/PolicyDto.yaml'
    ClaimDto:
      $ref: './components/schemas/ClaimDto.yaml'
    AutoClaimDto:
      $ref: './components/schemas/AutoClaimDto.yaml'
    HomeClaimDto:
      $ref: './components/schemas/HomeClaimDto.yaml'
    HealthClaimDto:
      $ref: './components/schemas/HealthClaimDto.yaml'
    AssignAdjusterDto:
      $ref: './components/schemas/AssignAdjusterRequestDto.yaml'
    EmployeeDto:
      $ref: './components/schemas/EmployeeDto.yaml'
    PolicyConditionsDto:
      $ref: './components/schemas/PolicyConditionsDto.yaml'
    CancellationPenaltyRuleDto:
      $ref: './components/schemas/CancellationPenaltyRuleDto.yaml'
    AgencyDto:
      $ref: './components/schemas/AgencyDto.yaml'
  parameters:
    CustomerId:
      name: id
      in: path
      description: "The unique identifier of the customer"
      required: true
      schema:
        type: integer
        format: int64
    PolicyId:
      name: id
      in: path
      description: "The unique identifier of the policy"
      required: true
      schema:
        type: integer
        format: int64
    ClaimId:
      name: id
      in: path
      description: "The unique identifier of the claim"
      required: true
      schema:
        type: integer
        format: int64
    EmployeeId:
      name: id
      in: path
      description: "The unique identifier of the employee"
      required: true
      schema:
        type: integer
        format: int64
    AgencyId:
      name: id
      in: path
      description: "The unique identifier of the agency"
      required: true
      schema:
        type: integer
        format: int64