openapi: 3.0.3
info:
  title: Insurance Company API
  description: A dummy API for an insurance company to manage customers, policies, and claims.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local Development server

# Paths are now defined correctly by referencing external files for each path item.
paths:
  /customers:
    $ref: './paths/customers_collection.yaml'
  /customers/{id}:
    $ref: './paths/customers_item.yaml'
  /customers/{id}/policies:
    $ref: './paths/customer_policies_collection.yaml'
  /policies:
    $ref: './paths/policies_collection.yaml'
  /policies/{id}:
    $ref: './paths/policies_item.yaml'
  /policies/{id}/claims:
    $ref: './paths/policies_claims_collection.yaml'
  /claims/{id}:
    $ref: './paths/claims_item.yaml'
  /claims/{id}/assign-adjuster:
    $ref: './paths/claims_assigment.yaml'
  /employees:
    $ref: './paths/employees_collection.yaml'
  /employees/{id}:
    $ref: './paths/employees_item.yaml'
  /policy-conditions:
    $ref: './paths/policy_conditions.yaml'
  /agencies:
    $ref: './paths/agencies_collection.yaml'
  /agencies/{id}:
    $ref: './paths/agencies_item.yaml'

# Components and schemas remain the same.
components:
  schemas:
    CustomerDto:
      $ref: './components/schemas/CustomerDto.yaml'
    AddressDto:
      $ref: './components/schemas/AddressDto.yaml'
    PolicyDto:
      $ref: './components/schemas/PolicyDto.yaml'
    ClaimDto:
      $ref: './components/schemas/ClaimDto.yaml'
    AssignAdjusterDto:
      $ref: './components/schemas/AssignAdjusterRequestDto.yaml'
    EmployeeDto:
      $ref: './components/schemas/EmployeeDto.yaml'
    PolicyConditionsDto:
      $ref: './components/schemas/PolicyConditionsDto.yaml'
    CancellationPenaltyRuleDto:
      $ref: './components/schemas/CancellationPenaltyRuleDto.yaml'
    AgencyDto:
      $ref: './components/schemas/AgencyDto.yaml'
  parameters:
    CustomerId:
      name: id
      in: path
      description: "The unique identifier of the customer"
      required: true
      schema:
        type: integer
        format: int64
    PolicyId:
      name: id
      in: path
      description: "The unique identifier of the policy"
      required: true
      schema:
        type: integer
        format: int64
    ClaimId:
      name: id
      in: path
      description: "The unique identifier of the claim"
      required: true
      schema:
        type: integer
        format: int64
    EmployeeId:
      name: id
      in: path
      description: "The unique identifier of the employee"
      required: true
      schema:
        type: integer
        format: int64
    AgencyId:
      name: id
      in: path
      description: "The unique identifier of the agency"
      required: true
      schema:
        type: integer
        format: int64